import type { BrandConfig } from '../lib/brandConfig.ts';

// Edit this file for site identity and theme; collection data stays in collection.json.
const name = 'CardThings';

export default {
  name,
  tagline: 'A home for good finds.',
  footerNote: 'Thoughtfully collected. Always within reach.',
  repositoryUrl: 'https://github.com/kylerlam/card-things',
  favicon: 'favicon.svg',
  metadata: {
    title: `${name} — A home for good finds`,
    description: `A little library of tools, ideas, and things worth coming back to. Explore the ${name} example collection.`,
  },
  // Exact existing colors, including interaction states. Image/category colors are separate.
  theme: {
    background: '#f7f8f5',
    surface: '#fff',
    text: '#20272a',
    'muted-text': '#687078',
    accent: '#214d3a',
    'accent-hover': '#163b29',
    'on-accent': '#fff',
    border: '#e1e5e2',
    'brand-mark': '#173d2e',
    'brand-text': '#172326',
    heading: '#173e2f',
    'focus-ring': '#478762',
    'focus-border': '#668e74',
    'focus-shadow': '#214d3a0d',
    'nav-label': '#667174',
    'nav-hover': '#f3f5f1',
    'nav-active': '#eaf0eb',
    'count-text': '#596961',
    breadcrumb: '#4d5557',
    'breadcrumb-muted': '#6b7377',
    'status-text': '#535d5b',
    'status-dot': '#498452',
    'input-border': '#dbe1dd',
    'input-icon': '#6a7578',
    placeholder: '#858c8d',
    'key-border': '#d9dedb',
    'subtle-surface': '#f4f5f3',
    'key-text': '#65706e',
    'key-shadow': '#00000008',
    'filter-text': '#626c70',
    'filter-hover': '#edf0ec',
    'sort-text': '#303b3b',
    'card-border': '#e2e7e1',
    'card-hover-border': '#c9d5cb',
    'card-shadow': '#20442b08',
    'cover-placeholder': '#e8ece5',
    'category-text': '#596362',
    'tag-border': '#e9ece7',
    'tag-text': '#5a6562',
    'icon-hover': '#ecf2ec',
    'favorite-text': '#5d6d64',
    'footer-text': '#646f68',
    'empty-border': '#d6ddd5',
    'empty-icon': '#7a9681',
    'notice-text': '#6c5831',
    'dialog-border': '#d5ded5',
    'dialog-shadow': '#132b3040',
    backdrop: '#10231b85',
    'close-shadow': '#00000010',
    'detail-description': '#64716b',
    'detail-text': '#56615c',
    'copy-hover': '#edf3ec',
    'copy-shadow': '#20442b15',
  },
} satisfies BrandConfig;
